### ISSUE TITLE
braintreepayments dependency

### ISSUE THREAD

**Issue by zanneee** [paypal/Checkout-Java-SDK#13]
Hi team,

Current Checkout-Java-SDK has braintreepayments dependency?

I can see the below codes in the sample.

> import com.braintreepayments.http.HttpResponse;
> import com.braintreepayments.http.exceptions.HttpException;

**Comment by zanneee** [comment]
Can we also have the installation guide?
e.g. https://github.com/paypal/PayPal-Java-SDK/wiki/Installation

**Comment by rajarampadmanathan** [comment]
Hi @zanneee - 

Yes, this SDK internally uses braintreehttp client to make HTTP calls. While setting up SDK using gradle/maven, this dependency will be automatically taken care off and no need add it explicitly.

Regarding installation guide,  If you want to setup SDK binaries, 
https://developer.paypal.com/docs/checkout/reference/server-integration/setup-sdk/ should help.
If you want to setup SDK source code, README.md has few info about it. Are you looking for any info which is not covered in these 2?

**Comment by zanneee** [comment]
Thanks for your help @rajarampadmanathan 👍
