### ISSUE TITLE
String Values are not correctly quoted for json

### ISSUE THREAD

**Issue by kerko** [paypal/Checkout-Java-SDK#15]
Consider an Article with the following Name: Notebook Aspire 1 (A114-32-P0K1) schwarz (14" FHD (matt)/Pen N5000/4GB/64GB eMMC)
A correct json representation of a Java Object with a field "name" which is field with the above value would look like this:
`{"name":"Notebook Aspire 1 (A114-32-P0K1) schwarz (14\" FHD (matt)/Pen N5000/4GB/64GB eMMC)"}`
But the sdk produces this:
`{"name":"Notebook Aspire 1 (A114-32-P0K1) schwarz (14" FHD (matt)/Pen N5000/4GB/64GB eMMC)"}`
Which is then denied from your server with this error:
`Caused by: com.braintreepayments.http.exceptions.HttpException: {"name":"INVALID_REQUEST","message":"Request is not well-formed, syntactically incorrect, or violates schema.","debug_id":"65dee0a14698d","details":[{"location":"body","issue":"Unexpected character ('F' (code 70)): was expecting comma to separate Object entries\n at [Source: (ByteArrayInputStream); line: 1, column: 781] line: 1, column: 733"}],"links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-Unexpected character ('F' (code 70)): was expecting comma to separate Object entries\n at [Source: (ByteArrayInputStream); line: 1, column: 781] line: 1, column: 733","rel":"information_link","encType":"application/json"}]}`

I think the sdk should correctly quote any string it serializes into json

**Comment by rajarampadmanathan** [comment]
Hi @kerko - Thanks for reporting this. I validated this and currently SDK doesn't do any special treatment for special characters. It just construct the JSON with provided details. 

**At this point, These special characters should be handled before setting the values in SDK POJO's.** 

I will discuss this with the team and get back to you if there is a plan to handle this fix at SDK layer.

**Comment by rajarampadmanathan** [comment]
@rsdighe76 - Can you please check this ?

**Comment by rsdighe76** [comment]
At this point there is no plans to enhance to support handling for special characters.
