### ISSUE TITLE
Client Authentication failed despite following PayPal guides

### ISSUE THREAD

**Issue by dgorczyca** [paypal/Checkout-Java-SDK#16]
Hi team,

After implementing basic checkout integration on front end (https://developer.paypal.com/docs/checkout/integrate/) I send request to my server app.

My server app has got PayPalClient setup with the test application's client ID and client secret for sandbox as per this guide https://developer.paypal.com/docs/checkout/reference/server-integration/setup-sdk/.

I am using Java SDK with SpringBoot app.
My REST controller after saving order ID it received from front end javascript app. Next it tries to contact PayPal using client:

import com.braintreepayments.http.HttpResponse;
import com.paypal.orders.Order;
```
...
OrdersGetRequest payPalRequest = new OrdersGetRequest(orderDTO.getOrderId());
payPalRequest.header("prefer", "return=representation");
log.info("Verifying details of client id {} and client secret {}", payPalClient.getClientId(), payPalClient.getClientSecret());
HttpResponse<Order> response = payPalClient.getClient().execute(payPalRequest);
Order payPalOrderResponse = response.result();
...
```

when I check the server logs, log info confirms correct client id and client secret are being used, yet I am getting the following exception:
```
com.braintreepayments.http.exceptions.HttpException: {"error":"invalid_client","error_description":"Client Authentication failed"}
at com.braintreepayments.http.HttpClient.parseResponse(HttpClient.java:198) ~[braintreehttp-1.3.1.jar!/:na]
at com.braintreepayments.http.HttpClient.execute(HttpClient.java:98) ~[braintreehttp-1.3.1.jar!/:na]
at com.paypal.core.AuthorizationProvider.fetchAccessToken(AuthorizationProvider.java:55) ~[checkout-sdk-1.0.0.jar!/:na]
at com.paypal.core.AuthorizationProvider.authorize(AuthorizationProvider.java:35) ~[checkout-sdk-1.0.0.jar!/:na]
at com.paypal.core.PayPalHttpClient.signRequest(PayPalHttpClient.java:39) ~[checkout-sdk-1.0.0.jar!/:na]
at com.braintreepayments.http.HttpClient.execute(HttpClient.java:93) ~[braintreehttp-1.3.1.jar!/:na]
```
Why would the same client ID work from the front-end while back end would throw this exception when getting the order?

I followed this guide for getting the transaction details:
https://developer.paypal.com/docs/checkout/reference/server-integration/get-transaction/#on-the-server

Is there anything else I should add/do?

**Comment by pengpeng11** [comment]
Hi Dawid, @dgorczyca 

- could you please confirm that you are pointing to the sandbox environment rather than live?
- if possible, could you please send us the `paypal debug id`? it is in the header of response.

Thanks.

**Comment by dgorczyca** [comment]
@pengpeng11 thank you for quick response.
I am 100% sure I am calling sandbox on both front-end and back-end

Here is the debug ID from capture request on the frontend client (this request works correctly and happens around the same time as the request from back-end )
https://www.sandbox.paypal.com/smart/api/order/1MU20385CH7909720/capture
Paypal-Debug-Id: e2a44bc488eef, e2a44bc488eef

Are you able to identify using this Paypal-Debug-Id requests that come from the same APP(ClientID) but from back-end server?

**Comment by pengpeng11** [comment]
> @pengpeng11 thank you for quick response.
> I am 100% sure I am calling sandbox on both front-end and back-end
> 
> Here is the debug ID from capture request on the frontend client (this request works correctly and happens around the same time as the request from back-end )
> https://www.sandbox.paypal.com/smart/api/order/1MU20385CH7909720/capture
> Paypal-Debug-Id: e2a44bc488eef, e2a44bc488eef
> 
> Are you able to identify using this Paypal-Debug-Id requests that come from the same APP(ClientID) but from back-end server?

Hi Dawid,
        I can search for the transaction with the client id. could you please provide the date/time when the authentication failure happened?

Peng

**Comment by dgorczyca** [comment]
Thank you @pengpeng11, sure here is the UTC time from the logs:
`2019-04-23 15:40:30.759 ERROR 6 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception com.braintreepayments.http.exceptions.HttpException: {"error":"invalid_client","error_description":"Client Authentication failed"}`

My client id is: AdIJkhtipsHFJ92JgvcfexmPXmV7Y3p7w3I0Y1KoGsjdTt4nl_xIRz4xpnN3Uz3990l5AndHp_3k2HnI

**Comment by pengpeng11** [comment]
@dgorczyca I have found the transaction and it seems there are some internal failure in token creation service call. I have already forward the logs to the team and will get back when I have it. As I see from the two debug Id you posted, it seems it works now correct?

**Comment by dgorczyca** [comment]
Thank you @pengpeng11, the Paypal-debug-id I sent was from the front-end application.
Back end was using the same clientID, yet it was also using client secret as per this guide:  https://developer.paypal.com/docs/checkout/reference/server-integration/setup-sdk/
It is the back-end service where we are experiencing authentication failure.

So in other words it is not working correctly on the back-end using Java SDK and the same credentials.

The log I showed you is from the back-end Java app, that is where it failed, thank you for looking into it. Please tell me if you need any more details.

**Comment by pengpeng11** [comment]
@dgorczyca Got update from team and it seems you are using the client id for sandbox to make the api call to live environment. Could you please double check? if possible, please paste the code block where you set the environment, we can help look into it.

**Comment by dgorczyca** [comment]
Hi @pengpeng11, how could I call production servers when my PayPalClient only had the code as it was in the guide:
`PayPalEnvironment environment new PayPalEnvironment.**Sandbox**(clientId, clientSecret) `

I have now added code to Production environment.
Is there any other setting than PayPalEnvironment that is passed to: `PayPalHttpClient(environment)`?

I will do further tests and come back to you.

**Comment by ganeshramc** [comment]
Hi @dgorczyca any update on this issue?

**Comment by ganeshramc** [comment]
Hi @dgorczyca, do you have update on this? Or if you have any other questions, feel free to open another issue. We'll close this in 7 days unless you have more questions related to this issue. Thanks!
