### ISSUE TITLE
CreateOrder response to client

### ISSUE THREAD

**Issue by john970473** [paypal/Checkout-Java-SDK#17]
After I use createOrder , I get Braintree http response of order.
How could I send  response to client smart button fetch API ?
I cannot convert Braintree http types to httpservlet response.
Could you please provide a sample for servlet?

**Comment by puppinoo** [comment]
Can you please tell me how you solved? I'm having the same issue.

**Comment by john970473** [comment]
you can response this type : new JSONObject(new Json().serialize(response.result()))
or you can just response "orderID" json type

**Comment by puppinoo** [comment]
Thanks for help. My issue was how I used the paypal "fetch" method. It always gave me empty response.

**Comment by john970473** [comment]
https://developer.paypal.com/docs/checkout/reference/server-integration/set-up-transaction/
You can follow this page.
On the client side
createOrder: function() {
  return fetch('/my-server/create-paypal-transaction', {
    method: 'post',
    headers: {
      'content-type': 'application/json'
    }
  }).then(function(res) {
    return res.json();
  }).then(function(data) {
    return data.orderID;
  });
}

You just request to create an order and get orderID, and then response {"orderID":"qweradsd123"} with json type.

**Comment by puppinoo** [comment]
Thanks. I didn't create an order. I created and later (after client approval) executed a payment. I wonder if it's the same. It looks like it worked though.
