### ISSUE TITLE
Discount Setting

### ISSUE THREAD

**Issue by john970473** [paypal/Checkout-Java-SDK#18]
I want to add discount to my order, but I could only add shipping discount instead of item discount.
I tried to add an item with negative value,but I failed and got CANNOT_BE_NEGATIVE.
How to add discount value or change the text on paypal order.

**Comment by pengpeng11** [comment]
@john970473 Hi John, our team is working on `discount` feature and will add support in SDK once it is in production.
For now, you can patch on your order to apply the discount.

**Comment by john970473** [comment]
"patch on your order to apply the discount"
What does this mean?

**Comment by ganeshramc** [comment]
@john970473 Take a look at this [patch order](https://github.com/paypal/Checkout-Java-SDK/blob/develop/checkout-sdk-sample/src/main/java/com/paypal/PatchOrder.java). At this specific line `patches.add(new Patch().op("replace").path("/purchase_units/@reference_id=='PUHF'/amount")
.value(new AmountWithBreakdown().currencyCode("USD").value("200.00")` the amount is replaced with a new amount. Similarly, replace your amount with `amount - discount` and patch it.

**Comment by dpavlov222** [comment]
when are you planning to introduce ability to add Discount ? At this moment I can't add some discount when I make instance of OrdersCreateRequest.

**Comment by ganeshramc** [comment]
Hey @dpavlov222, try using order patch when you're applying discounts. You can always change the amount later like I have detailed above!

**Comment by dpavlov222** [comment]
@ganeshramc but if I understand correctly before patching order I need to create order and during order creation I have to specify all order items, shipping , discounts and amount to show it correctly at the PayPal popup
![image](https://user-images.githubusercontent.com/52283780/60603976-6af0ef80-9dbf-11e9-99cb-360730be9849.png)

**Comment by LordlingZhang** [comment]
hi~  i used patch ，my order_create request is 
![image](https://user-images.githubusercontent.com/20698566/60874344-71251700-a26a-11e9-8ee2-b25e08487ebe.png)，but when i patch 
![image](https://user-images.githubusercontent.com/20698566/60874408-8a2dc800-a26a-11e9-8e69-03260f2ecf51.png)
response error 
![image](https://user-images.githubusercontent.com/20698566/60874448-a2054c00-a26a-11e9-9855-51f494337507.png)
can you help me?
thanks~

**Comment by ganeshramc** [comment]
Hey so we have actually fixed this now with the new version 1.0.1
You should be able to pass in discount now!
