### ISSUE TITLE
“Access Token not found in cache” we got this error respose from last10 hours

### ISSUE THREAD

**Issue by super-ok** [paypal/Checkout-Java-SDK#24]
e:{"error":"invalid_token","error_description":"Access Token not found in cache"},
this error happened in create order and get order api call, we had no changing in our java server, so i think there must be some wrong in PayPal "cache" service。

**Comment by ganeshramc** [comment]
Hey @super-ok, it is caached in your server and paypal does not have any cache service. Is this still happening?

**Comment by super-ok** [comment]
> Hey @super-ok, it is caached in your server and paypal does not have any cache service. Is this still happening?

no, it recovered with nothing to do, it remained about 10hours.

**Comment by ganeshramc** [comment]
Great. Please reach out again if it happens again. Thanks!
