### ISSUE TITLE
Maven dependency is not working

### ISSUE THREAD

**Issue by Sharathnasa** [paypal/Checkout-Java-SDK#25]
Hi,

I'm trying to add the below maven dependency to the project, but it's not able to download the dependency.

```
<dependency>
    <groupId>com.paypal.sdk</groupId>
    <artifactId>checkout-sdk</artifactId>
    <version>1.0.1</version>
</dependency>
```

Getting the error:
`
Cannot resolve com.paypal.sdk:checkout-sdk:1.0.1`

**Comment by rajarampadmanathan** [comment]
Hi, Can you please check if you're pointing the maven central repository? I can see jar file is present in the central repository.
https://repo.maven.apache.org/maven2/com/paypal/sdk/checkout-sdk/1.0.1/

**Comment by Sharathnasa** [comment]
Yes, i'm referring to the same. It's not working.
