### ISSUE TITLE
How are the REST API JSON mappings generated?

### ISSUE THREAD

**Issue by richardscarrott** [paypal/Checkout-Java-SDK#26]
To be frank I know next to nothing about Java but...

I'm using the [Checkout-NodeJS-SDK](https://github.com/paypal/Checkout-NodeJS-SDK/) with TypeScript. However, there are no TypeScript typings for the [PayPal objects](https://developer.paypal.com/docs/api/orders/v2/#definitions) but I can see this [Java SDK has JSON mappings](https://github.com/paypal/Checkout-Java-SDK/blob/develop/checkout-sdk/src/main/java/com/paypal/orders/Order.java).

Are they automatically generated and if so from where? It'd be great if we could use the same source to generate TypeScript types?

**Comment by richardscarrott** [comment]
Additionally, as an aside, the REST docs aren't clear re: which fields are required or not. e.g. https://developer.paypal.com/docs/api/orders/v2/#definition-order

Some properties such as [`payer.address_portable.country_code`](https://developer.paypal.com/docs/api/orders/v2/#definition-payer.address_portable) explicitly say the field is "required", but other properties such as [`order.id`](https://developer.paypal.com/docs/api/orders/v2/#definition-order) are not...it seems very odd to think that the `order.id` isn't always present in the JSON response?

**Comment by rsdighe76** [comment]
order id is a result (response) hence it is not required. 

required fields are annotated in orange - please see screen shott
![Screen Shot 2020-06-02 at 3 15 16 PM](https://user-images.githubusercontent.com/207491/83575246-f39e7100-a4e3-11ea-9467-3f7437f3f0d0.png)
