### ISSUE TITLE
Malformed json - missing pair delimiter

### ISSUE THREAD

**Issue by LordlingZhang** [paypal/Checkout-Java-SDK#27]
![image](https://user-images.githubusercontent.com/20698566/67551846-6ec4cb00-f73c-11e9-9e4d-c0b840cde552.png)
hi ,team:
When I call the interface (/v2/checkout/orders/{order_id}), an exception occurs on the image, but the request parameter has only order_id. Why is this happening?
Waiting for reply~
Thank you~

**Comment by tiffanyrzhou** [comment]
@LordlingZhang  Thank you for reaching out. Can you provide me with an order ID/ enviroment where this exception occur? The problem shouldn't be in the request. It looks like the exception is being thrown when the http client receives the response. Take a look a the response that is returned, that may be a starting point.

**Comment by LordlingZhang** [comment]
Because the value of the returned json string contains double quotes, sdk parsing error
