### ISSUE TITLE
Invalid client id error when using sandbox credentials in a test in Jenkins

### ISSUE THREAD

**Issue by dimple2015** [paypal/Checkout-Java-SDK#33]
Hi,
I am using the CreateOrder class and methods here in a RestAssured test class using my sandbx credentials. The test runs fine locally but when I deploy the test to Jenkins, it fails with the following error and stack trace:
----------------------
**Error Message**
com.paypal.http.exceptions.HttpException: {"error":"invalid_client","error_description":"Client Authentication failed"}
**Stacktrace**
com.paypal.http.exceptions.HttpException: {"error":"invalid_client","error_description":"Client Authentication failed"}
	at com.paypal.http.HttpClient.parseResponse(HttpClient.java:200)
	at com.paypal.http.HttpClient.execute(HttpClient.java:98)
	at com.paypal.core.AuthorizationProvider.fetchAccessToken(AuthorizationProvider.java:55)
	at com.paypal.core.AuthorizationProvider.authorize(AuthorizationProvider.java:35)
	at com.paypal.core.PayPalHttpClient.signRequest(PayPalHttpClient.java:40)
	at com.paypal.http.HttpClient.execute(HttpClient.java:93)
	at user.CreateOrder.createOrder(CreateOrder.java:52)

----------
I invoke the following in my setup() in my test class. 
 PayPalEnvironment environment = new PayPalEnvironment.Sandbox(
               Parameters.paypal_sandbox_client_id,
               Parameters.paypal_sandbox_client_secret)
        if(environment != null) {
            PayPalHttpClient client = new PayPalHttpClient(environment);
            if(client != null) {
                HttpResponse<Order> order = new CreateOrder().createOrder(client, true);
                if(order != null) {
                    String purchaseOrderId = order.result().id();
                }
            }
        }
    }
Would appreciate your help ASAP. 

Thanks!
Dimple

**Comment by tiffanyrzhou** [comment]
Hello @dimple2015 Given that your credentials are working in locally, at this time we do not believe it is a problem with the sdk and more so with jenkins setup. We will try our best to provide guidance on this manner. If you can provide a paypal-debug-id, we can try to investigate further.
Thanks!
